server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/top-ten
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # create, create-drop, validate, update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: true
    open-in-view: false

  flyway:
    enabled: false

#  h2:
#    console.enabled: true
#    console.path: /h2-console


#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: YOUR_GOOGLE_APP_CLIENT_ID
#            clientSecret: YOUR_GOOGLE_APP_SECRET_KEY
#            scope:
#              - email
#              - profile
#
#          facebook:
#            clientId: YOUR_FACEBOOK_APP_CLIENT_ID
#            clientSecret: YOUR_FACEBOOK_APP_SECRET_KEY
#            scope:
#              - email
#              - public_profile

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0


management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"

service:
  scrapers:
    basketball-reference-url: "https://www.basketball-reference.com/"
    nba-stats: "https://www.nba.com/stats/"