server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # create, create-drop, validate, update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: true
    open-in-view: false

  flyway:
    enabled: false

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

          facebook:
            clientId: ${FACEBOOG_CLIENT_ID}
            clientSecret: ${FACEBOOK_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
    health:
      show-details: always

service:
  admin-users: yoav200@gmail.com, roey.alhalel@gmail.com
  scrapers:
    basketball-reference-url: "https://www.basketball-reference.com/"
    nba-stats: "https://www.nba.com/stats/"
    min-games-limit: 82
  players:
    random-fetch-size: 4
  ranking:
    editors-choice: 432
    min-ranking: 1
    max-ranking: 50
  social:
    max-comment-by-user: 8
    max-comment-length: 256
    min-comment-length: 10