server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # create, create-drop, validate, update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
