server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: false
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
