server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/top-ten
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # create, create-drop, validate, update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: true
    open-in-view: false

  flyway:
    enabled: false

  #  h2:
  #    console.enabled: true
  #    console.path: /h2-console

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 964718617611-le13opabiecm49gfnblh2p1jqd29s1h5.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

          facebook:
            clientId: 362211486075851
            clientSecret: a968f53b0ff30b660ca6f85842a97e99
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0


management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
    health:
      show-details: always

service:
  admin-users: yoav200@gmail.com, roey.alhalel@gmail.com
  scrapers:
    basketball-reference-url: "https://www.basketball-reference.com/"
    nba-stats: "https://www.nba.com/stats/"
    min-games-limit: 82
  players:
    random-fetch-size: 4
  ranking:
    editors-choice: 432
    min-ranking: 1
    max-ranking: 50
  social:
    max-comment-by-user: 8
    max-comment-length: 256
    min-comment-length: 10